port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:2222
external-ui: yacd-gh-pages
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
    - https://dns.google/dns-query
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
#Trojan
  - name: TROJAN SG
    server: sg.oppaineverdie.my.id
    port: 443
    type: trojan
    password: 17662887-1465-4acf-a6a3-8694c79a63b5
    skip-cert-verify: true
    sni: meet.google.com
    network: ws
    ws-opts:
      path: /trojan-tls
      headers:
        Host: sg.oppaineverdie.my.id
    udp: true
#Shadowsocks
  - name: SHADOWSOCKS ID
    type: ss
    server: idsocks.ipservers.xyz
    port: 1443
    cipher: aes-256-cfb
    password: IIE8iB7R0J
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: meet.google.com
  - name: SHADOWSOCKS SG
    type: ss
    server: sg1socks.ipservers.xyz
    port: 1443
    cipher: aes-256-cfb
    password: aaUwOzj48U
    udp: true
    plugin: obfs
    plugin-opts:
      mode: tls
      host: meet.google.com
proxy-groups:
  - name: VPN
    type: select
    proxies:
    - TROJAN SG
    - SHADOWSOCKS ID
    - SHADOWSOCKS SG
    - DIRECT

rules:
 - MATCH,VPN
